### ISSUE TITLE
Linux Port

### ISSUE THREAD

**Issue by Baneeishaque** [APK-Multi-Tool/APK-Multi-Tool#30]
Is there any linux port?

**Comment by clmowers** [comment]
https://github.com/APK-Multi-Tool/APK-Multi-Tool-Linux

**Comment by Baneeishaque** [comment]
ok

On 4/8/16, clmowers <notifications@github.com> wrote:
> https://github.com/APK-Multi-Tool/APK-Multi-Tool-Linux
>
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/APK-Multi-Tool/APK-Multi-Tool/issues/30#issuecomment-207047362


-- 
Banee Ishaque K

**Comment by Baneeishaque** [comment]
Invite
    

    
        

            
                
                    
                        
                    
                    
                                                

                


                
                    Dear APK-Multi-Tool/APK-Multi-Tool, 

                    
                        I found a simple way to save on all purchases. CashbackURL.in is just a one click process to earn cashback.
                        Before buying from any of the 500+ Indian online stores, just open www.cashbackURL.in and search for store or copy paste product URL. And, continue buying normally from the store. 
                        Cashback gets tracked and you can redeem the amount for either mobile recharge or cash payment. 
                    

                    
                        Click here to Activate your Account
                    

                    ( Since I'm referring you, clicking on the above link creates an account instantly. And, you can immediately start earning on cashbackURL )

                    
                        Cheers,
                        Banee Ishaque K 
                    
                

                This email has been sent by cashbackURL on behalf of your friend, Banee Ishaque K. 
                    Click here to Unsubscribe if you don't want to receive any emails in future.

                
            


            © LOCUS Web Services Pvt. Ltd.,2nd Floor, Pochampally House, 1-10-72/A/2, above Nike Showroom, 
                Beside Nalli Silks, SP Road, Begumpet,Telangana, India.

**Comment by Baneeishaque** [comment]
Best Rated Business Networking App

Hey APK-Multi-Tool/APK-Multi-Tool,

Get thousands of quality business leads for FREE and network with fellow
business owners on Feedwiser.

Best Regards,Banee Ishaque K

Accept Invite

Don't have the app yet? Download now for real-time notifications and more.

Sent by Feedwiser. 
If you wish to stop receiving email alerts, click on Unsubscribe.

**Comment by Baneeishaque** [comment]
Best Rated Business Networking App

Banee Ishaque K would like to connect on Feedwiser. How would you like to
respond?

Banee Ishaque K

Banee Ishaque K

Accept Invite

Don't have the app yet? Download now for real-time notifications and more.

Sent by Feedwiser. 
If you wish to stop receiving email alerts, click on Unsubscribe.
